# Output wav file name
wav : isomap.wav
# Output json file name
json : isomap.json
# Name of input data
input_data : analysis_data/mfcc.json
# How many points to reduce the initial data set to
pre_reduction : 0
# Choose the algorithm for the second dim reduction (TSNE, ISOMAP, UMAP)
algorithm : ISOMAP
# Do you want to output a plot from this?
plot : true