# Output wav file name
wav : tsne.wav
# Output json file name
json : tsne.json
# Name of input data
input_data : analysis_data/mfcc.json
# How many points to reduce the initial data set to
pre_reduction : 50
# Choose the algorithm for the second dim reduction (TSNE, ISOMAP, UMAP)
algorithm : TSNE
# Do you want to output a plot from this?
plot : true