# Output wav file name
wav : isomap.wav
# Output json file name
json : isomap.json
# Name of input data
input_data : mfcc_RAW.json
# How many points to reduce the initial data set to
pre_reduction : 30
# Choose the algorithm for the second dim reduction (TSNE or ISOMAP)
algorithm : TSNE
# Do you want to output a plot from this?
plot : true