# Output json file name
json : ahc_250.json
# Name of input data
input_data : UMAP_7-1/umap.json
# Choose the algorithm for clustering (DBSCAN, [A]ffinity[P]ropogation)
algorithm : AP
normalisation : none
identifier : UMAP-7-1-ahc_250
tog_plot : true
ap_n_clusters : 250