# Output json file name
json : ahc_3200.json
# Name of input data
input_data : UMAP_7-1/umap.json
# Choose the algorithm for clustering (DBSCAN, [A]ffinity[P]ropogation)
algorithm : AP
normalisation : none
identifier : UMAP-7-1-ahc_3200
tog_plot : false
ap_n_clusters : 3200