json : lin_svm_classification.json
# Name of input data

input_data : mfcc_RAW.json

# Choose the algorithm - choices are:
# Naive Bayes (NB) 
# Logistic Regression (LR)
# State Vector Machine (SVM)
# MLP Neural Network (MLP)
# linearSVM (linSVC)
# random forest (RF)
# N.B. These are case sensitive.
algorithm : linSVC

# Choose the kind of data normalisation you want before it goes into the classifier.
# You can choose minmax, standardise or none.
normalisation : standardise